/*

 BGMAP1.H

 Map Include File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 20 x 18
   Tile set      : bgtile1.gbr
   Plane count   : 1 plane (8 bits)
   Plane order   : Tiles are continues
   Tile offset   : 0
   Split data    : No

 This file was generated by GBMB v1.8

*/

#define bgmap1Width 20
#define bgmap1Height 18
#define bgmap1Bank 0

extern unsigned char bgmap1[];

/* End of BGMAP1.H */
