/*

 BGMAP4.H

 Map Include File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 20 x 18
   Tile set      : bgtile1.gbr
   Plane count   : 1 plane (8 bits)
   Plane order   : Tiles are continues
   Tile offset   : 0
   Split data    : No

 This file was generated by GBMB v1.8

*/

#define bgmap4Width 20
#define bgmap4Height 18
#define bgmap4Bank 0

extern unsigned char bgmap4[];

/* End of BGMAP4.H */
