/*

 WHALE_POSTER.H

 Include File.

 Info:
  Form                 : All tiles as one unit.
  Format               : Gameboy 4 color.
  Compression          : None.
  Counter              : None.
  Tile size            : 32 x 32
  Tiles                : 0 to 0

  Palette colors       : None.
  SGB Palette          : None.
  CGB Palette          : None.

  Convert to metatiles : No.

 This file was generated by GBTD v2.2

*/

#include <gb/gb.h>
/* Bank of tiles. */
#define TileWhalePosterBank 1
/* Start of tile array. */
extern unsigned char TileWhalePoster[];

extern UBYTE TileWhalePosterLength;

/* End of WHALE_POSTER.H */
