/*

 HIGHSCORE_TABLE.H

 Map Include File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 20 x 9
   Tile set      : C:\dev\Code\gameboy\SWorld\sprites and maps\8x8 font.gbr
   Plane count   : 1 plane (8 bits)
   Plane order   : Tiles are continues
   Tile offset   : 0
   Split data    : No

 This file was generated by GBMB v1.8

*/

#define highscore_table_mapWidth 20
#define highscore_table_mapHeight 9
#define highscore_table_mapBank 0

extern unsigned char highscore_table_map[];

/* End of HIGHSCORE_TABLE.H */
