/*

 LEVEL_DATA1.H

 Map Include File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 15 x 380
   Tile set      : C:\dev\Code\gameboy\drop\tiles\leveltiles.gbr
   Plane count   : 1 plane (8 bits)
   Plane order   : Tiles are continues
   Tile offset   : 0
   Split data    : No

 This file was generated by GBMB v1.8

*/

#define level_data1Width 15
#define level_data1Height 380
#define level_data1Bank 0

extern unsigned char level_data1[];

/* End of LEVEL_DATA1.H */
